project_id = "rwmqfgnlzawlklpfwfqu"

[functions.admin_edit_punch]
verify_jwt = false

[functions.admin_dashboard]
verify_jwt = false

[functions.employee_dashboard]
verify_jwt = false

[functions.clock_in]
verify_jwt = false

[functions.clock_out]
verify_jwt = false

[functions.face_enroll]
verify_jwt = false