import { createContext, useContext, useState, ReactNode } from "react";

type Lang = "es" | "en";

const translations = {
  es: {
    hello: "Hola",
    managerPanel: "Panel de Gerente",
    employeePanel: "Panel de Empleado",
    activeEmployees: "Empleados Activos",
    outEmployees: "Empleados Fuera",
    remainingLicense: "Licencia Restante",
    punchesToday: "Marcaciones Hoy",
    weeklyAttendance: "Asistencia Semanal",
    liveMonitoring: "Monitoreo en Vivo",
    hoursPerEmployee: "Horas por Empleado",
    noEmployees: "Sin empleados registrados",
    active: "Activo",
    out: "Fuera",
    inactive: "Inactivo",
    noRecord: "Sin registro",
    trialDays: "días de prueba",
    attendances: "Asistencias",
    team: "Equipo",
    reports: "Reportes",
    settings: "Ajustes",
    panel: "Panel",
    clock: "Reloj",
    history: "Historial",
    closeSession: "Cerrar Sesión",
    administrator: "Administrador",
    employee: "Empleado",
    // Employee dashboard
    attendanceControl: "Control de asistencia",
    onShift: "En Jornada",
    offShift: "Fuera de Jornada",
    startShift: "Iniciar",
    endShift: "Finalizar",
    shift: "Jornada",
    today: "Hoy",
    week: "Semana",
    geofence: "Geovalla",
    gpsVerified: "GPS Verificado",
    lowAccuracy: "Baja Precisión",
    acquiring: "Adquiriendo...",
    detectedLocation: "Ubicación detectada",
    errorMargin: "Margen de Error",
    meters: "metros",
    weeklyActivity: "Actividad Semanal",
    pending: "Pendiente",
    completed: "Completado",
    loading: "Cargando...",
    noRecordsYet: "Sin registros aún",
    shiftStarted: "¡Jornada iniciada!",
    shiftEnded: "¡Jornada finalizada!",
    startError: "Error al iniciar",
    endError: "Error al finalizar",
    gpsError: "No se pudo obtener tu ubicación. Activa el GPS.",
    browserNoGeo: "Tu navegador no soporta geolocalización.",
    // Employee management
    manageEmployees: "Gestión de Empleados",
    createEmployee: "Crear Empleado",
    editEmployee: "Editar Empleado",
    fileEmployee: "Archivar",
    activateEmployee: "Activar",
    name: "Nombre",
    email: "Email",
    role: "Rol",
    status: "Estado",
    actions: "Acciones",
    save: "Guardar",
    cancel: "Cancelar",
    filed: "Inactivo",
    activeStatus: "Activo",
    editPunch: "Editar Marcación",
    clockIn: "Entrada",
    clockOut: "Salida",
    editPunches: "Editar Marcaciones",
    recentPunches: "Marcaciones Recientes",
    employeeHistory: "Historial de Asistencia",
    filterByDate: "Filtrar por fecha",
    from: "Desde",
    to: "Hasta",
    totalHours: "Total Horas",
    totalEntries: "Total Registros",
    avgPerDay: "Promedio/Día",
    date: "Fecha",
    entry: "Entrada",
    exit: "Salida",
    duration: "Duración",
    location: "Ubicación",
    noHistoryFound: "No se encontraron registros para el rango seleccionado",
    allTime: "Todo el tiempo",
    thisWeek: "Esta Semana",
    thisMonth: "Este Mes",
    lastMonth: "Mes Pasado",
    custom: "Personalizado",
    apply: "Aplicar",
    exportCsv: "Exportar CSV",
    // Locations
    locations: "Ubicaciones",
    manageLocations: "Gestión de Ubicaciones",
    createLocation: "Crear Ubicación",
    editLocation: "Editar Ubicación",
    locationName: "Nombre de Ubicación",
    address: "Dirección",
    latitude: "Latitud",
    longitude: "Longitud",
    errorMarginMeters: "Margen de Error (metros)",
    assignLocation: "Asignar Ubicación",
    noLocation: "Sin ubicación",
    locationSaved: "Ubicación guardada",
    locationDeleted: "Ubicación eliminada",
    deleteLocation: "Eliminar Ubicación",
    confirmDeleteLocation: "¿Estás seguro de eliminar esta ubicación?",
    assignedLocation: "Ubicación Asignada",
    noLocations: "Sin ubicaciones registradas",
    poweredBy: "Desarrollado por",
    // Billing & Plans
    planBilling: "Plan y Facturación",
    currentPlan: "Plan Actual",
    seatsUsed: "Asientos Usados",
    planExpires: "Vence",
    upgradePlan: "Mejorar Plan",
    seatLimitReached: "Límite de asientos alcanzado",
    planEssential: "Essential",
    planProfessional: "Professional",
    planEnterprise: "Enterprise",
    planTrial: "Prueba",
    contactSales: "Contactar Ventas",
    selectPlan: "Seleccionar",
    planUpdated: "Plan actualizado",
    suspendedBanner: "Tu cuenta está suspendida. Actualiza tu plan para restaurar el acceso completo.",
    gracePeriodBanner: "Tu plan venció. Tienes un periodo de gracia de 5 días.",
    noChargesYet: "Sin cargos por ahora",
    billingPeriod: "Periodo de facturación",
    monthly: "Mensual",
    annual: "Anual",
  },
  en: {
    hello: "Hello",
    managerPanel: "Manager Panel",
    employeePanel: "Employee Panel",
    activeEmployees: "Active Employees",
    outEmployees: "Employees Out",
    remainingLicense: "Remaining License",
    punchesToday: "Punches Today",
    weeklyAttendance: "Weekly Attendance",
    liveMonitoring: "Live Monitoring",
    hoursPerEmployee: "Hours per Employee",
    noEmployees: "No employees registered",
    active: "Active",
    out: "Out",
    inactive: "Inactive",
    noRecord: "No record",
    trialDays: "trial days",
    attendances: "Attendance",
    team: "Team",
    reports: "Reports",
    settings: "Settings",
    panel: "Panel",
    clock: "Clock",
    history: "History",
    closeSession: "Log Out",
    administrator: "Administrator",
    employee: "Employee",
    attendanceControl: "Attendance control",
    onShift: "On Shift",
    offShift: "Off Shift",
    startShift: "Start",
    endShift: "End",
    shift: "Shift",
    today: "Today",
    week: "Week",
    geofence: "Geofence",
    gpsVerified: "GPS Verified",
    lowAccuracy: "Low Accuracy",
    acquiring: "Acquiring...",
    detectedLocation: "Detected location",
    errorMargin: "Error Margin",
    meters: "meters",
    weeklyActivity: "Weekly Activity",
    pending: "Pending",
    completed: "Completed",
    loading: "Loading...",
    noRecordsYet: "No records yet",
    shiftStarted: "Shift started!",
    shiftEnded: "Shift ended!",
    startError: "Error starting shift",
    endError: "Error ending shift",
    gpsError: "Could not get your location. Enable GPS.",
    browserNoGeo: "Your browser does not support geolocation.",
    manageEmployees: "Employee Management",
    createEmployee: "Create Employee",
    editEmployee: "Edit Employee",
    fileEmployee: "File",
    activateEmployee: "Activate",
    name: "Name",
    email: "Email",
    role: "Role",
    status: "Status",
    actions: "Actions",
    save: "Save",
    cancel: "Cancel",
    filed: "Inactive",
    activeStatus: "Active",
    editPunch: "Edit Punch",
    clockIn: "Clock In",
    clockOut: "Clock Out",
    editPunches: "Edit Punches",
    recentPunches: "Recent Punches",
    employeeHistory: "Attendance History",
    filterByDate: "Filter by date",
    from: "From",
    to: "To",
    totalHours: "Total Hours",
    totalEntries: "Total Entries",
    avgPerDay: "Avg/Day",
    date: "Date",
    entry: "Entry",
    exit: "Exit",
    duration: "Duration",
    location: "Location",
    noHistoryFound: "No records found for the selected range",
    allTime: "All Time",
    thisWeek: "This Week",
    thisMonth: "This Month",
    lastMonth: "Last Month",
    custom: "Custom",
    apply: "Apply",
    exportCsv: "Export CSV",
    // Locations
    locations: "Locations",
    manageLocations: "Location Management",
    createLocation: "Create Location",
    editLocation: "Edit Location",
    locationName: "Location Name",
    address: "Address",
    latitude: "Latitude",
    longitude: "Longitude",
    errorMarginMeters: "Error Margin (meters)",
    assignLocation: "Assign Location",
    noLocation: "No location",
    locationSaved: "Location saved",
    locationDeleted: "Location deleted",
    deleteLocation: "Delete Location",
    confirmDeleteLocation: "Are you sure you want to delete this location?",
    assignedLocation: "Assigned Location",
    noLocations: "No locations registered",
    poweredBy: "Powered by",
    // Billing & Plans
    planBilling: "Plan & Billing",
    currentPlan: "Current Plan",
    seatsUsed: "Seats Used",
    planExpires: "Expires",
    upgradePlan: "Upgrade Plan",
    seatLimitReached: "Seat limit reached",
    planEssential: "Essential",
    planProfessional: "Professional",
    planEnterprise: "Enterprise",
    planTrial: "Trial",
    contactSales: "Contact Sales",
    selectPlan: "Select",
    planUpdated: "Plan updated",
    suspendedBanner: "Your account is suspended. Upgrade your plan to restore full access.",
    gracePeriodBanner: "Your plan has expired. You have a 5-day grace period.",
    noChargesYet: "No charges for now",
    billingPeriod: "Billing period",
    monthly: "Monthly",
    annual: "Annual",
  },
} as const;

type TranslationKey = keyof typeof translations.es;

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem("app-lang");
    return (saved === "en" || saved === "es") ? saved : "es";
  });

  const changeLang = (l: Lang) => {
    setLang(l);
    localStorage.setItem("app-lang", l);
  };

  const t = (key: TranslationKey): string => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
